version: "3.6"

services:
  redis:
    image: redis/redis-stack:7.4.0-v0
    ports:
      - 6379:6379
      - 13333:8001
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - /Users/jxhui/Developer/redis/data:/data


  postgres:
    image: postgres:16
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - /Users/jxhui/Developer/redis/data/psql:/var/lib/postgresql/data
